import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

class PDFExportService {
  constructor() {
    this.doc = null;
  }

  // Initialize PDF document
  initPDF() {
    this.doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
  }

  // Add header with logo and title
  addHeader(title) {
    const pageWidth = this.doc.internal.pageSize.width;
    
    // Add colored header bar
    this.doc.setFillColor(37, 99, 235);
    this.doc.rect(0, 0, pageWidth, 20, 'F');
    
    // Add title
    this.doc.setTextColor(255, 255, 255);
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(title, 20, 13);
    
    // Add date
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    const dateStr = format(new Date(), 'MMMM dd, yyyy');
    this.doc.text(dateStr, pageWidth - 50, 13);
    
    // Reset text color
    this.doc.setTextColor(0, 0, 0);
  }

  // Add footer with page numbers
  addFooter() {
    const pageCount = this.doc.internal.getNumberOfPages();
    const pageWidth = this.doc.internal.pageSize.width;
    
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(8);
      this.doc.setTextColor(128, 128, 128);
      this.doc.text(
        `Page ${i} of ${pageCount} - Generated by Hireup`,
        pageWidth / 2 - 40,
        this.doc.internal.pageSize.height - 10
      );
    }
  }

  // Add user info section
  addUserInfo(user, fileName) {
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Resume Analysis Report', 20, 35);
    
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`User: ${user?.name || 'Guest'}`, 20, 45);
    this.doc.text(`Email: ${user?.email || 'Not logged in'}`, 20, 52);
    this.doc.text(`Resume: ${fileName || 'Unknown'}`, 20, 59);
    this.doc.text(`Generated: ${format(new Date(), 'MMMM dd, yyyy - hh:mm a')}`, 20, 66);
  }

  // Add score card
  addScoreCard(atsScore, matchScore, passedChecks, totalChecks) {
    const startY = 80;
    
    // Background for score card
    this.doc.setFillColor(248, 250, 252);
    this.doc.roundedRect(20, startY, 170, 40, 3, 3, 'F');
    
    // ATS Score
    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(37, 99, 235);
    this.doc.text(`${atsScore}%`, 30, startY + 25);
    
    this.doc.setFontSize(8);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(100, 116, 139);
    this.doc.text('ATS Score', 30, startY + 32);
    
    // Match Score (if exists)
    if (matchScore > 0) {
      this.doc.setFontSize(24);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(245, 158, 11);
      this.doc.text(`${matchScore}%`, 90, startY + 25);
      
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(100, 116, 139);
      this.doc.text('Job Match', 90, startY + 32);
    }
    
    // Checks passed
    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(16, 185, 129);
    this.doc.text(`${passedChecks}/${totalChecks}`, 150, startY + 25);
    
    this.doc.setFontSize(8);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(100, 116, 139);
    this.doc.text('Checks Passed', 150, startY + 32);
  }

  // Add skills section
  addSkills(skills, missingSkills) {
    let yPos = 130;
    
    // Skills found
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(31, 41, 55);
    this.doc.text('Skills Found', 20, yPos);
    
    yPos += 5;
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(75, 85, 99);
    
    const skillsText = skills.slice(0, 15).join(' • ');
    const splitSkills = this.doc.splitTextToSize(skillsText, 170);
    this.doc.text(splitSkills, 20, yPos + 5);
    
    yPos += splitSkills.length * 5 + 10;
    
    // Missing skills (if any)
    if (missingSkills && missingSkills.length > 0) {
      this.doc.setFontSize(12);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(239, 68, 68);
      this.doc.text('Skills to Add', 20, yPos);
      
      yPos += 5;
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(75, 85, 99);
      
      const missingText = missingSkills.slice(0, 15).join(' • ');
      const splitMissing = this.doc.splitTextToSize(missingText, 170);
      this.doc.text(splitMissing, 20, yPos + 5);
      
      yPos += splitMissing.length * 5 + 15;
    } else {
      yPos += 5;
    }
    
    return yPos;
  }

  // Add checklist table
  addChecklist(checklist) {
    const tableColumn = ['Checklist Item', 'Status', 'Category'];
    const tableRows = [];
    
    checklist.forEach(item => {
      const status = item.passed ? '✅ Passed' : '❌ Failed';
      tableRows.push([item.name, status, item.category || 'General']);
    });
    
    this.doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 160,
      theme: 'striped',
      headStyles: {
        fillColor: [37, 99, 235],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252]
      },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 40, halign: 'center' },
        2: { cellWidth: 40 }
      }
    });
  }

  // Add suggestions section
  addSuggestions(suggestions) {
    const finalY = this.doc.lastAutoTable.finalY + 10;
    
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(31, 41, 55);
    this.doc.text('Improvement Suggestions', 20, finalY);
    
    let yPos = finalY + 10;
    suggestions.forEach((suggestion, index) => {
      // Category badge
      this.doc.setFillColor(37, 99, 235);
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(255, 255, 255);
      this.doc.roundedRect(20, yPos - 4, 30, 6, 1, 1, 'F');
      this.doc.text(suggestion.category, 22, yPos);
      
      // Message
      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(31, 41, 55);
      const splitMessage = this.doc.splitTextToSize(suggestion.message, 150);
      this.doc.text(splitMessage, 55, yPos - 2);
      
      yPos += splitMessage.length * 5 + 8;
      
      // Action (if exists)
      if (suggestion.action) {
        this.doc.setFontSize(9);
        this.doc.setFont('helvetica', 'italic');
        this.doc.setTextColor(100, 116, 139);
        const splitAction = this.doc.splitTextToSize(`💡 ${suggestion.action}`, 160);
        this.doc.text(splitAction, 22, yPos - 2);
        yPos += splitAction.length * 5 + 5;
      }
      
      yPos += 5;
    });
  }

  // Add GitHub section
  addGitHubSection(githubData) {
    if (!githubData) return;
    
    const yPos = this.doc.lastAutoTable?.finalY + 10 || 200;
    
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(31, 41, 55);
    this.doc.text('GitHub Profile', 20, yPos);
    
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(75, 85, 99);
    this.doc.text(`Username: ${githubData.username}`, 20, yPos + 8);
    this.doc.text(`Repositories: ${githubData.repos?.length || 0}`, 20, yPos + 15);
    this.doc.text(`Followers: ${githubData.followers || 0}`, 100, yPos + 15);
  }

  // Generate complete PDF report
  async generateReport(analysis, user, fileName, githubData) {
    this.initPDF();
    
    this.addHeader('Hireup Resume Analysis');
    this.addUserInfo(user, fileName);
    this.addScoreCard(
      analysis.atsScore,
      analysis.matchScore,
      analysis.passedChecks,
      analysis.totalChecks
    );
    
    const yPos = this.addSkills(analysis.skills, analysis.missingSkills);
    
    // Add new page if needed
    if (yPos > 220) {
      this.doc.addPage();
      this.addHeader('Hireup Resume Analysis (Continued)');
    }
    
    this.addChecklist(analysis.checklist);
    this.addSuggestions(analysis.suggestions);
    this.addGitHubSection(githubData);
    this.addFooter();
    
    // Save the PDF
    this.doc.save(`Hireup-Report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  }
}

export default PDFExportService;
